[2021-03-07 11:36:10,056] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.generate 2021-03-07T11:36:09.461651+00:00 [queued]>
[2021-03-07 11:36:10,063] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.generate 2021-03-07T11:36:09.461651+00:00 [queued]>
[2021-03-07 11:36:10,063] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 11:36:10,063] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 11:36:10,063] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 11:36:10,076] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): generate> on 2021-03-07T11:36:09.461651+00:00
[2021-03-07 11:36:10,083] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio_2', 'generate', '2021-03-07T11:36:09.461651+00:00', '--job-id', '95', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_minio_2/main.py', '--cfg-path', '/tmp/tmprg2gpngy', '--error-file', '/tmp/tmpppu0gnch']
[2021-03-07 11:36:10,084] {standard_task_runner.py:77} INFO - Job 95: Subtask generate
[2021-03-07 11:36:10,080] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2021-03-07 11:36:10,114] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio_2.generate 2021-03-07T11:36:09.461651+00:00 [running]> on host b5d0ebb2b610
[2021-03-07 11:36:10,138] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_minio_2
AIRFLOW_CTX_TASK_ID=generate
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T11:36:09.461651+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T11:36:09.461651+00:00
[2021-03-07 11:36:10,155] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_minio_2, task_id=generate, execution_date=20210307T113609, start_date=20210307T113610, end_date=20210307T113610
[2021-03-07 11:36:10,171] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-07 11:36:10,177] {local_task_job.py:146} INFO - Task exited with return code 0
