[2021-03-03 21:20:13,916] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_1.repeat 2021-03-03T21:20:11.831154+00:00 [queued]>
[2021-03-03 21:20:13,927] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_1.repeat 2021-03-03T21:20:11.831154+00:00 [queued]>
[2021-03-03 21:20:13,927] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:20:13,927] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 21:20:13,927] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:20:13,933] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): repeat> on 2021-03-03T21:20:11.831154+00:00
[2021-03-03 21:20:13,937] {standard_task_runner.py:52} INFO - Started process 54 to run task
[2021-03-03 21:20:13,939] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_1', 'repeat', '2021-03-03T21:20:11.831154+00:00', '--job-id', '54', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test-1/main.py', '--cfg-path', '/tmp/tmpuu3jieqw', '--error-file', '/tmp/tmpf_j742eg']
[2021-03-03 21:20:13,939] {standard_task_runner.py:77} INFO - Job 54: Subtask repeat
[2021-03-03 21:20:13,997] {logging_mixin.py:104} INFO - Running <TaskInstance: test_1.repeat 2021-03-03T21:20:11.831154+00:00 [running]> on host 4c61e128b408
[2021-03-03 21:20:14,029] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=test_1
AIRFLOW_CTX_TASK_ID=repeat
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T21:20:11.831154+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T21:20:11.831154+00:00
[2021-03-03 21:20:14,046] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=test_1, task_id=repeat, execution_date=20210303T212011, start_date=20210303T212013, end_date=20210303T212014
[2021-03-03 21:20:14,065] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-03 21:20:14,071] {local_task_job.py:146} INFO - Task exited with return code 0
