[2021-03-07 19:49:18,054] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_to_kafka_1.send 2021-03-07T19:49:17.096290+00:00 [queued]>
[2021-03-07 19:49:18,060] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_to_kafka_1.send 2021-03-07T19:49:17.096290+00:00 [queued]>
[2021-03-07 19:49:18,060] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:49:18,060] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:49:18,060] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:49:18,071] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): send> on 2021-03-07T19:49:17.096290+00:00
[2021-03-07 19:49:18,075] {standard_task_runner.py:52} INFO - Started process 58 to run task
[2021-03-07 19:49:18,077] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_to_kafka_1', 'send', '2021-03-07T19:49:17.096290+00:00', '--job-id', '179', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/send_to_kafka_1/main.py', '--cfg-path', '/tmp/tmp3_8ooxdz', '--error-file', '/tmp/tmpr1zsi26b']
[2021-03-07 19:49:18,077] {standard_task_runner.py:77} INFO - Job 179: Subtask send
[2021-03-07 19:49:18,128] {logging_mixin.py:104} INFO - Running <TaskInstance: send_to_kafka_1.send 2021-03-07T19:49:17.096290+00:00 [running]> on host 7531d0e32fd2
[2021-03-07 19:49:18,154] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=send_to_kafka_1
AIRFLOW_CTX_TASK_ID=send
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T19:49:17.096290+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T19:49:17.096290+00:00
[2021-03-07 19:49:18,160] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=send_to_kafka_1, task_id=send, execution_date=20210307T194917, start_date=20210307T194918, end_date=20210307T194918
[2021-03-07 19:49:18,176] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:49:18,210] {local_task_job.py:146} INFO - Task exited with return code 0
