[2021-03-07 13:07:30,633] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: check_minio_2.check_s3_for_file_in_s3 2021-03-07T13:07:29.426536+00:00 [queued]>
[2021-03-07 13:07:30,643] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: check_minio_2.check_s3_for_file_in_s3 2021-03-07T13:07:29.426536+00:00 [queued]>
[2021-03-07 13:07:30,643] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 13:07:30,644] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 13:07:30,644] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 13:07:30,654] {taskinstance.py:1063} INFO - Executing <Task(S3KeySensor): check_s3_for_file_in_s3> on 2021-03-07T13:07:29.426536+00:00
[2021-03-07 13:07:30,658] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2021-03-07 13:07:30,661] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'check_minio_2', 'check_s3_for_file_in_s3', '2021-03-07T13:07:29.426536+00:00', '--job-id', '114', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/check_minio_2/main.py', '--cfg-path', '/tmp/tmp2pfa3_ez', '--error-file', '/tmp/tmpwhljl12o']
[2021-03-07 13:07:30,661] {standard_task_runner.py:77} INFO - Job 114: Subtask check_s3_for_file_in_s3
[2021-03-07 13:07:30,687] {logging_mixin.py:104} INFO - Running <TaskInstance: check_minio_2.check_s3_for_file_in_s3 2021-03-07T13:07:29.426536+00:00 [running]> on host ded171213b30
[2021-03-07 13:07:30,718] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=check_minio_2
AIRFLOW_CTX_TASK_ID=check_s3_for_file_in_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T13:07:29.426536+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T13:07:29.426536+00:00
[2021-03-07 13:07:30,718] {s3_key.py:98} INFO - Poking for key : s3://my-first-bucket/*.txt*
[2021-03-07 13:07:30,719] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=local_minio
[2021-03-07 13:07:30,727] {base_aws.py:164} INFO - Credentials retrieved from extra_config
[2021-03-07 13:07:30,727] {base_aws.py:81} INFO - Creating session with aws_access_key_id=minio-access-key region_name=None
[2021-03-07 13:07:30,739] {base_aws.py:151} INFO - role_arn is None
[2021-03-07 13:07:30,802] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=local_minio
[2021-03-07 13:07:30,807] {base_aws.py:164} INFO - Credentials retrieved from extra_config
[2021-03-07 13:07:30,807] {base_aws.py:81} INFO - Creating session with aws_access_key_id=minio-access-key region_name=None
[2021-03-07 13:07:30,818] {base_aws.py:151} INFO - role_arn is None
[2021-03-07 13:07:30,864] {base.py:245} INFO - Success criteria met. Exiting.
[2021-03-07 13:07:30,871] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=check_minio_2, task_id=check_s3_for_file_in_s3, execution_date=20210307T130729, start_date=20210307T130730, end_date=20210307T130730
[2021-03-07 13:07:30,895] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 13:07:30,913] {local_task_job.py:146} INFO - Task exited with return code 0
