[2021-03-03 21:22:29,283] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_email.prepare_email 2021-03-03T21:22:27.652988+00:00 [queued]>
[2021-03-03 21:22:29,292] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_email.prepare_email 2021-03-03T21:22:27.652988+00:00 [queued]>
[2021-03-03 21:22:29,292] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:22:29,292] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 21:22:29,292] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:22:29,298] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): prepare_email> on 2021-03-03T21:22:27.652988+00:00
[2021-03-03 21:22:29,301] {standard_task_runner.py:52} INFO - Started process 54 to run task
[2021-03-03 21:22:29,304] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_email', 'prepare_email', '2021-03-03T21:22:27.652988+00:00', '--job-id', '61', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/send_email/main.py', '--cfg-path', '/tmp/tmpv4x_3cu2', '--error-file', '/tmp/tmp6u6glbjk']
[2021-03-03 21:22:29,304] {standard_task_runner.py:77} INFO - Job 61: Subtask prepare_email
[2021-03-03 21:22:29,328] {logging_mixin.py:104} INFO - Running <TaskInstance: send_email.prepare_email 2021-03-03T21:22:27.652988+00:00 [running]> on host 4c61e128b408
[2021-03-03 21:22:29,356] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=send_email
AIRFLOW_CTX_TASK_ID=prepare_email
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T21:22:27.652988+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T21:22:27.652988+00:00
[2021-03-03 21:22:29,390] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=send_email, task_id=prepare_email, execution_date=20210303T212227, start_date=20210303T212229, end_date=20210303T212229
[2021-03-03 21:22:29,409] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-03 21:22:29,436] {local_task_job.py:146} INFO - Task exited with return code 0
