[2021-03-03 22:46:33,928] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_3.bash_test 2021-03-03T22:46:31.786089+00:00 [queued]>
[2021-03-03 22:46:33,939] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_3.bash_test 2021-03-03T22:46:31.786089+00:00 [queued]>
[2021-03-03 22:46:33,940] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 22:46:33,940] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 22:46:33,940] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 22:46:33,945] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): bash_test> on 2021-03-03T22:46:31.786089+00:00
[2021-03-03 22:46:33,949] {standard_task_runner.py:52} INFO - Started process 48 to run task
[2021-03-03 22:46:33,952] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio_3', 'bash_test', '2021-03-03T22:46:31.786089+00:00', '--job-id', '86', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_minio_3/main.py', '--cfg-path', '/tmp/tmpfzeqlun_', '--error-file', '/tmp/tmpna2u0yu4']
[2021-03-03 22:46:33,952] {standard_task_runner.py:77} INFO - Job 86: Subtask bash_test
[2021-03-03 22:46:33,978] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio_3.bash_test 2021-03-03T22:46:31.786089+00:00 [running]> on host b5d0ebb2b610
[2021-03-03 22:46:34,004] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=save_to_minio_3
AIRFLOW_CTX_TASK_ID=bash_test
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T22:46:31.786089+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T22:46:31.786089+00:00
[2021-03-03 22:46:34,004] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-03 22:46:34,004] {bash.py:158} INFO - Running command: echo "hello, it should work" > s3_conn_test.txt
[2021-03-03 22:46:34,013] {bash.py:169} INFO - Output:
[2021-03-03 22:46:34,013] {bash.py:177} INFO - Command exited with return code 0
[2021-03-03 22:46:34,032] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_minio_3, task_id=bash_test, execution_date=20210303T224631, start_date=20210303T224633, end_date=20210303T224634
[2021-03-03 22:46:34,048] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-03 22:46:34,084] {local_task_job.py:146} INFO - Task exited with return code 0
