[2021-03-07 19:06:17,330] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_3.save 2021-03-07T19:06:16.280345+00:00 [queued]>
[2021-03-07 19:06:17,341] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_clickhouse_3.save 2021-03-07T19:06:16.280345+00:00 [queued]>
[2021-03-07 19:06:17,342] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:06:17,342] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-07 19:06:17,342] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-07 19:06:17,348] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): save> on 2021-03-07T19:06:16.280345+00:00
[2021-03-07 19:06:17,351] {standard_task_runner.py:52} INFO - Started process 54 to run task
[2021-03-07 19:06:17,354] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_clickhouse_3', 'save', '2021-03-07T19:06:16.280345+00:00', '--job-id', '143', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_clickhouse_3/main.py', '--cfg-path', '/tmp/tmpwzd6k_im', '--error-file', '/tmp/tmp36052ghe']
[2021-03-07 19:06:17,354] {standard_task_runner.py:77} INFO - Job 143: Subtask save
[2021-03-07 19:06:17,381] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_clickhouse_3.save 2021-03-07T19:06:16.280345+00:00 [running]> on host 020f66ce59e6
[2021-03-07 19:06:17,410] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_clickhouse_3
AIRFLOW_CTX_TASK_ID=save
AIRFLOW_CTX_EXECUTION_DATE=2021-03-07T19:06:16.280345+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-07T19:06:16.280345+00:00
[2021-03-07 19:06:17,498] {logging_mixin.py:104} INFO - [(datetime.datetime(2021, 3, 7, 19, 6, 17), '21.2.4.6')]
[2021-03-07 19:06:17,508] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_clickhouse_3, task_id=save, execution_date=20210307T190616, start_date=20210307T190617, end_date=20210307T190617
[2021-03-07 19:06:17,532] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-07 19:06:17,566] {local_task_job.py:146} INFO - Task exited with return code 0
