[2021-03-03 21:07:36,428] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.generate 2021-03-03T21:07:34.819395+00:00 [queued]>
[2021-03-03 21:07:36,437] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: save_to_minio_2.generate 2021-03-03T21:07:34.819395+00:00 [queued]>
[2021-03-03 21:07:36,437] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:07:36,437] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 21:07:36,437] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 21:07:36,443] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): generate> on 2021-03-03T21:07:34.819395+00:00
[2021-03-03 21:07:36,446] {standard_task_runner.py:52} INFO - Started process 46 to run task
[2021-03-03 21:07:36,448] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'save_to_minio_2', 'generate', '2021-03-03T21:07:34.819395+00:00', '--job-id', '43', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/save_to_mino_2/main.py', '--cfg-path', '/tmp/tmpsrb2gxea', '--error-file', '/tmp/tmpszmqasvf']
[2021-03-03 21:07:36,449] {standard_task_runner.py:77} INFO - Job 43: Subtask generate
[2021-03-03 21:07:36,471] {logging_mixin.py:104} INFO - Running <TaskInstance: save_to_minio_2.generate 2021-03-03T21:07:34.819395+00:00 [running]> on host 4c61e128b408
[2021-03-03 21:07:36,493] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=save_to_minio_2
AIRFLOW_CTX_TASK_ID=generate
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T21:07:34.819395+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T21:07:34.819395+00:00
[2021-03-03 21:07:36,507] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=save_to_minio_2, task_id=generate, execution_date=20210303T210734, start_date=20210303T210736, end_date=20210303T210736
[2021-03-03 21:07:36,527] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-03 21:07:36,541] {local_task_job.py:146} INFO - Task exited with return code 0
