[2021-03-03 18:31:54,583] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_email.prepare_email 2021-03-03T18:31:52.264724+00:00 [queued]>
[2021-03-03 18:31:54,592] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: send_email.prepare_email 2021-03-03T18:31:52.264724+00:00 [queued]>
[2021-03-03 18:31:54,592] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 18:31:54,592] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-03 18:31:54,592] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-03 18:31:54,597] {taskinstance.py:1063} INFO - Executing <Task(_PythonDecoratedOperator): prepare_email> on 2021-03-03T18:31:52.264724+00:00
[2021-03-03 18:31:54,601] {standard_task_runner.py:52} INFO - Started process 51 to run task
[2021-03-03 18:31:54,603] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_email', 'prepare_email', '2021-03-03T18:31:52.264724+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/send_email.py', '--cfg-path', '/tmp/tmpudm5e50g', '--error-file', '/tmp/tmpsn4ue47a']
[2021-03-03 18:31:54,603] {standard_task_runner.py:77} INFO - Job 21: Subtask prepare_email
[2021-03-03 18:31:54,625] {logging_mixin.py:104} INFO - Running <TaskInstance: send_email.prepare_email 2021-03-03T18:31:52.264724+00:00 [running]> on host 02b058bbf526
[2021-03-03 18:31:54,652] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=iotoi
AIRFLOW_CTX_DAG_ID=send_email
AIRFLOW_CTX_TASK_ID=prepare_email
AIRFLOW_CTX_EXECUTION_DATE=2021-03-03T18:31:52.264724+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-03T18:31:52.264724+00:00
[2021-03-03 18:31:54,678] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=send_email, task_id=prepare_email, execution_date=20210303T183152, start_date=20210303T183154, end_date=20210303T183154
[2021-03-03 18:31:54,694] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-03 18:31:54,735] {local_task_job.py:146} INFO - Task exited with return code 0
